# martin-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-tiler
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vector-tiler
  template:
    metadata:
      labels:
        app: vector-tiler
    spec:
      containers:
      - name: vector-tiler
        image: ghcr.io/maplibre/martin:latest 
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        args:
          - "/files"
        volumeMounts:
        - name: tile-storage
          mountPath: /files
          readOnly: true
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: tile-storage
        persistentVolumeClaim:
          claimName: tile-pvc
          readOnly: true
        