# django-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-tiler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vector-tiler
  template:
    metadata:
      labels:
        app: vector-tiler
    spec:
      containers:
      - name: vector-tiler
        image: ghcr.io/maplibre/martin:latest 
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_POOL_SIZE
          value: "100"
        - name: KEEP_ALIVE
          value: "100"
        - name: WORKER_PROCESSES
          value: "10"
        - name: DANGER_ACCEPT_INVALID_CERTS
          value: "FALSE"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_URL