# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: npm
  directory: '/frontend'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - pronitdas
  assignees:
    - pronitdas
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
- package-ecosystem: maven
    directory: "/backend/etl/osm-pbf-tiles/planetiler-openmaptiles"
    open-pull-requests-limit: 10
    schedule:
      interval: daily
      time: '00:00'
    labels:
      - dependencies
      - maven
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
- package-ecosystem: pip
  directory: '/backend/core-monolith/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - pronitdas
  assignees:
    - pronitdas
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - pronitdas
  assignees:
    - pronitdas
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
