apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: migration-container
          image: pronittardis/db:latest
          env:
            - name: DJANGO_DEBUG
              value: "False"
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DBNAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
          command: 
            - /bin/sh
            - -c
            - "python manage.py migrate --noinput"
      restartPolicy: Never 