apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      containers:
        - name: migration-container
          image: pronittardis/db:latest
          env:
            - name: DJANGO_DEBUG
              value: "False"
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: dba-secrets
                  key: DB_DATABASE 
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: dba-secrets
                  key: POSTGRESQL_USER
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: "postgres-service"
            - name: POSTGRESQL_PASS
              valueFrom:
                secretKeyRef:
                  name: dba-secrets
                  key: POSTGRESQL_PASS
          command: ["python3 manage.py migrate"]
      restartPolicy: Never
