apiVersion: v1
kind: PersistentVolume
metadata:
  name: tile-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeBindingMode: Immediate
  local:
    path: /mnt/d/storage/tile