# django-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-app
  template:
    metadata:
      labels:
        app: core-app
    spec:
      containers:
      - name: core-app
        image: pronittardis/core-app:v1 
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: core-secrets
              key: DJANGO_SECRET_KEY
        - name: DJANGO_DEBUG
          value: "False"
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: dba-secrets
              key: DB_DATABASE 
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dba-secrets
              key: POSTGRESQL_USER
        - name: DB_PORT
          value: "5432"
        - name: DB_HOST
          value: "postgres-service"
        - name: POSTGRESQL_PASS
          valueFrom:
            secretKeyRef:
              name: dba-secrets
              key: POSTGRESQL_PASS