name: Docker Build

on:
  push:
    branches:
      - main
      - cit
  pull_request:
    branches:
      - cit
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get current version
      id: version
      run: echo ::set-output name=VERSION::$(git describe --tags --abbrev=0 || echo "0.1.0")

    - name: Build Docker image
      run: docker build -t tardisdigital/core-app:${{ steps.version.outputs.VERSION }} ./backend/core-monolith/
    - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker image
      run: docker push your-image-name
